'use client';
import { SessionProvider } from 'next-auth/react';
import Navbar from '../../components/Layout/Navbar';
import axiosClient from '../../config/api';
import { ContextProvider } from '../../contexts/context';
import './globals.css';
import type { Metadata } from 'next';

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default  function RootLayout({ children }: RootLayoutProps) {
  
  return (
    <html lang="pt-br">
      <SessionProvider>
        <ContextProvider>
          <body className="min-h-[100vh]">
            <Navbar />
            {children}
          </body>
        </ContextProvider>
      </SessionProvider>
    </html>
  );
}
