'use client';
import { SessionProvider } from 'next-auth/react';
import Navbar from '../../components/Layout/Navbar';
import { ContextProvider } from '../../contexts/context';
import './globals.css';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

interface RootLayoutProps {
  children: React.ReactNode;
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <SessionProvider>
        <ContextProvider>
          <body className="min-h-[100vh]">
            <ToastContainer />
            <Navbar />
            {children}
          </body>
        </ContextProvider>
      </SessionProvider>
    </html>
  );
}
